config/routes.rb
Rails.application.routes.draw do

  resources :accounts do
    resources :transaccions
    # Hack feo por error de tipeo
    resources :transaccions, :path => 'transactions', :as => 'transactions'
  end

  get 'accounts/:id/categories', to: 'accounts#show_categories', as:'account_categories'
  root 'accounts#index'

  resources :categories

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :transactions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories_transactions.rb
class CategoryTransaction < ApplicationRecord
  belongs_to :category
  belongs_to :my_transaction, class_name: 'Transaction'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_transaction
  has_many :my_transaction, class_name: 'Transaction', through: :category_transaction
end

app/models/category_transaction.rb
class CategoryTransaction < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :my_transaction, class_name: 'Transaction', optional: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
  has_many :category_transaction
  has_many :categories, through: :category_transaction
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
  end

  def create
    @account = Account.new(account_params)

    if @account.save
      redirect_to @account
    else
      render 'new'
    end
  end

  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
    @total_amount = @account.transactions.sum('amount')
    # Se separan en la parte que suma a la cuenta y en la que resta.
    @debe = @account.transactions.where('amount < 0').sum('amount')
    @haber = @total_amount - @debe # Notese que debe es negativo, por lo cual se despeja restando (T = H + D)
  end

  def show_categories
    @account = Account.find(params[:id])

    @resultado = {}

    @joined_view = @account.transactions.joins(:categories)
    Rails.logger.debug(@joined_view.inspect)
    Category.find_each do |category|
      @amount = @joined_view.where(categories: {id: category.id}).sum('amount')
      Rails.logger.debug(@amount.inspect)
      @resultado[category.name] = @amount unless @amount.zero?
    end
  end

  private

  def account_params
    params.require(:account).permit(:name, :id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def update
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def destroy
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name,
                                     :description)
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
  end

  def new
  end

  def update
  end

  def create
  end

  def destroy
  end

  def show
  end
end

app/controllers/transaccions_controller.rb
class TransaccionsController < ApplicationController
  def get
  end

  def new
    @account = Account.find(params[:account_id])
    @transaccion = @account.transactions.build
    @categories = Category.all
  end

  def edit
    @account = Account.find(params[:account_id])
    @transaccion = @account.transactions.find(params[:id])
  end

  def update
    @account = Account.find(params[:account_id])
    @transaccion = @account.transactions.find(params[:id])
    @categories = Category.all

    # No quiero que se agreguen tags infinitamente.
    @transaccion.categories.clear
    @categories = Category.find(category_param[:category_id])

    @categories.each do |category|
      @transaccion.categories << category
    end

    Rails.logger.info(@transaccion.errors.inspect)

    if @transaccion.update(transaccion_params)
      redirect_to account_path(@account)
    else
      render 'edit'
    end
  end
  def create
    unless params[:transaction].nil? or params[:account_id].nil?
      @account = Account.find(params[:account_id])
      @transaccion = @account.transactions.create(transaccion_params)

      @categories = Category.find(category_param[:category_id])

      @categories.each do |category|
        @transaccion.categories << category
      end

      if @transaccion.save
        redirect_to account_path(@account)
      else
        render 'new'
      end

    else
      render 'new'
    end
  end

  def destroy
    @account = Account.find(params[:account_id])
    @transaction = @account.transactions.find(params[:id])
    @transaction.destroy
    redirect_to account_path(@account)
  end

  def show
    @account = Account.find(params[:account_id])
    @transaction = @account.transactions.find(params[:id])
    @categories = @transaction.categories
  end

  private

  def transaccion_params
    params.require(:transaction).permit(:name,
                                        :amount,
                                        :transaction_date,
                                        :account_id,
                                        :comments).except(:category_id)
  end

  def category_param
    params.require(:transaction)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/transaccion_helper.rb
module TransaccionHelper
end

app/views/accounts/index.html.erb
<h1>Cuentas</h1>
<ul>
<% @accounts.each do |account| %>
  <li><%= account.name %> - <%= link_to 'Show', account_path(account) %> </li>
<% end %>
</ul>
<p><%= link_to 'Crear cuenta', new_account_path %></p>

app/views/accounts/new.html.erb
<h1>Crear Usuario</h1>
<%=form_with model:Account.new, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/accounts/show.html.erb
<h1> <%=@account.name.capitalize %> </h1>

<ul>
  <% @account.transactions.each do |transaccion| %>
    <li><%=transaccion.id %> - <%= transaccion.name %> - 
      <%= transaccion.amount %> - <%= link_to 'Show', account_transaccion_path(@account, transaccion) %> 
      - <%= link_to 'Eliminar', account_transaccion_path(@account, transaccion), method: :delete, data: { confirm: 'Esta seguro?'} %> </li>
  <% end %>
</ul>
<p> <strong>Debe:</strong> <%= @debe %></p>
<p> <strong>Haber:</strong> <%= @haber %></p>
<p> <strong>Total:</strong> <%= @total_amount %>

<p> <%= link_to 'Crear transaccion', new_account_transaccion_path(@account.id) %> - 
    <%= link_to 'Ver categorias', categories_path %> - <%= link_to 'Resumen por categorías', account_categories_path(@account) %></p>

app/views/accounts/show_categories.html.erb
<h1>Resultados por categoría para <%= @account.name %></h1>

<table>
  <tr>
    <th>Categoría</th>
    <th>Balance</th>
  </tr>
  <% @resultado.each do |name, amount| %>
    <tr>
      <td><%= name %></td>
      <td><%= amount %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Volver', account_path(@account) %>

app/views/categories/index.html.erb
<h1>Categorías</h1>
<ul>
<% @categories.each do |category| %>
  <li><%= category.name %> - <%= link_to 'Show', category_path(category) %> -
    <%= link_to 'Delete', category_path(category), method: :delete, 
    data: { confirm: 'Está seguro?'} %></li>
<% end %>
</ul>
<div>
  <%= link_to 'Crear categoría', new_category_path %> -
  <%= link_to 'Usuarios', accounts_path %>
</div>

app/views/categories/new.html.erb
<h1>Crear categoría</h1>

<%= form_with model:@category do |form| %>
  <p> 
    <%= form.label :name %> <br>
    <%= form.text_field :name%>
  </p>
  <p>
    <%= form.label :description %> <br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/categories/show.html.erb
<h1>Categoría</h1>
<h2> <%= @category.name %> </h2>

<div>
  <strong>Descripción:</strong> <%= @category.description %>
</div>

<div>
  <%= link_to 'Volver', categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetPage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transaccions/_create.html.erb
<h1>Hacer transacción</h1>
<%= form_with model: [@account, @transaccion], local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :amount %><br>
    <%= form.text_field :amount %>
  </p>
 
  <p>
    <%= form.label :transaction_date %><br>
    <%= form.date_select :transaction_date%>
  </p>
  <p>
    <%= form.label :comments %><br>
    <%= form.text_area :comments %>
  </p>
  <p>
    <%= form.label 'Categoría' %>
    <%= form.collection_select :category_id, Category.all, :id, :name, {include_hidden: false}, {multiple: true}  %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/transaccions/delete.html.erb
<h1>Transaccion#delete</h1>
<p>Find me in app/views/transaccion/delete.html.erb</p>

app/views/transaccions/edit.html.erb
<%= render partial:'transaccions/create', object: @transaccion %>
<%= link_to 'Atras', account_transaccion_path(params[:account_id], params[:id]) %>

app/views/transaccions/get.html.erb
<h1>Transaccion#get</h1>
<p>Find me in app/views/transaccion/get.html.erb</p>

app/views/transaccions/new.html.erb
<%= render 'transaccions/create' %>

<%= link_to 'Atras', account_path(:account_id) %>

app/views/transaccions/show.html.erb
<h1>Transaccion <%= @transaction.id %></h1>

<p>
  Nombre: <%= @transaction.name %>
</p>
<p>
  Cantidad: <%= @transaction.amount %>
</p>
<p>
  Fecha: <%= @transaction.transaction_date %>
</p>
<p>
  Comentarios: <%= @transaction.comments %>
</p>
<p>
  <strong> Categorías: </strong>
<% @categories.each do |category| %>
  <%= category.name %>
<% end %>
</p>
<%= link_to 'Editar', edit_account_transaccion_path(@account, @transaction) %>
<%= link_to 'Atras', account_path(@account) %>